### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by GlobalYam** [MarkusOttela/ot-harjoitustyo#1]
ladattu ja testattu:
13.45
3.5.2023

- Työn arviointi koitui varsin haastavaksi sillä ohjelman toiminnallisuus vaikutti riippuvan datasta jonka käyttäjän tulisi itse tuottaa.
- Merkittävä osa logiikasta koski myös kryptografiaa, jonka arviointi koitui haastavaksi ilman syvempää perehtymisä aiheeseen.
- Projektissa on valtava määrä python tiedostoja, dokumentaatio on kuitenkin suoritettu erittäin hyvin, joten funktioista voi saada selvää pelkästään lukemalla koodia
- 'poetry run invoke coverage_terminal' ja muut coverageen liittyvät poetry komennot eivät toimineet laitteellani, mutta en ole varma onko kyseessä yhteensopivuusongelma
- Kaikkiaan projekti vaikutti erittäin hyvin suoritetulta, en löytänyt mitään mihin ehdottaa perusteltua parannusta tai muutosehdotusta, hyvä suoritus!

**Comment by MarkusOttela** [comment]
>Työn arviointi koitui varsin haastavaksi sillä ohjelman toiminnallisuus vaikutti riippuvan datasta jonka käyttäjän tulisi itse tuottaa.

Joo työ oli merkittävän keskeneräinen vielä tuossa vaiheessa, nyt ohjelma tarjoaa valmiita aineksia tietokannassa, ja käyttöohjeet neuvovat miten testata toiminnallisuus läpi

* [x] Korjattu


<br><br>

>Merkittävä osa logiikasta koski myös kryptografiaa, jonka arviointi koitui haastavaksi ilman syvempää perehtymisä aiheeseen.

Kryptografinen puoli on suht läpinäkyvä osanen osana salattuja tietokantoja, lähtökohtaisesti
* `selkokielinen_data --> Salain(avain) --> salattu data`
* `salattu_data       --> Salain(avain) --> selkokielinen_data`

Itse avainderivointi, primitiivien oikean käytön arviointi jne on ymmärrettävästi erikoisosaamista eikä sitä omastakaan mielestänikään tarvitse tehdä vertaisarvioinnissa.
<br><br>

>Projektissa on valtava määrä python tiedostoja, dokumentaatio on kuitenkin suoritettu erittäin hyvin, joten funktioista voi saada selvää pelkästään lukemalla koodia

Tiedostojen määrää on vähän kutistettu ja rakennetta on järjestetty järkevämmäksi. Uudelleenkäytettävien UI-elementtien rakennus jää tulevaisuuden hommaksi.

* [x] Korjattu osin
<br><br>

>'poetry run invoke coverage_terminal' ja muut coverageen liittyvät poetry komennot eivät toimineet laitteellani, mutta en ole varma onko kyseessä yhteensopivuusongelma

Tästä en valitettavasti osaa sanoa.
<br><br>

>Kaikkiaan projekti vaikutti erittäin hyvin suoritetulta, en löytänyt mitään mihin ehdottaa perusteltua parannusta tai muutosehdotusta, hyvä suoritus!

Kiitos erinomaisesta palautteesta! Tiketti suljettu :tada:
